export const GET_ONE_BOOK = "GET_ONE_BOOK";
export const GET_ONE_BOOK_ERROR = "GET_ONE_BOOK_ERROR";
export const GET_ONE_BOOK_SUCCESS = "GET_ONE_BOOK_SUCCESS";

export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_ALL_BOOKS_ERROR = "GET_ALL_BOOKS_ERROR";
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS";

export const GET_ALL_AUTHORS = "GET_ALL_AUTHORS";
export const GET_ALL_AUTHORS_ERROR = "GET_ALL_AUTHORS_ERROR";
export const GET_ALL_AUTHORS_SUCCESS = "GET_ALL_AUTHORS_SUCCESS";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_ERROR = "GET_ALL_CATEGORIES_ERROR";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";

export const POST_REGISTER = "POST_REGISTER";
export const POST_REGISTER_ERROR = "POST_REGISTER_ERROR";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";

export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";